### ISSUE TITLE
Can you share example data for testing?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [Fiquem/Expression-Packing#1]
Good job!!!

Can you share the example data for testing? it's difficult to understand without data format

thanks!!

**Comment by Fiquem** [comment]
Hi!

Thank you for being interested in our code!

I'm afraid I can't supply our testing data as it is not free. However I can give a small explanation to create your own testing data.

It is necessary that your Source and Target meshes have the same number of vertices and same vertex topology! For example, a vertex on the mouth corner of the Source mesh corresponds to the same vertex on the same mouth corner on the Target mesh. 

- Place your source_neutral.obj and all of the source blendshapes (source_blendshape_1.obj ... source_blendshape_n.obj) in meshes/

- Place the target_neutral.obj in target_meshes/

- To create data for the symmetries/ folder, please open either your source_neutral.obj or target_neutral.obj in Maya. Use the paint select tool to select the top area of the left eye. Export these vertex numbers to a .txt file. Clear selection. Select the bottom area of the left eye. Export. Clear. 
  
  - Repeat this for each of the following areas: Eye Left Top, Eye Left Bottom, Eye Right Top, Eye Right Bottom, Mouth Top, Mouth Bottom, Face Left, Face Right.

  - To select Face Left and Face Right, if your mesh is symmetric around the vertical axis (as most face meshes are!), I suggest using Maya's symmetry select.

  - Save these .txt files as character_sym0.txt, character_sym1.txt ... character_sym7.txt in symmetries/

I hope this helps! :D

**Comment by ZHANG-SHI-CHANG** [comment]
> Hi!
> 
> Thank you for being interested in our code!
> 
> I'm afraid I can't supply our testing data as it is not free. However I can give a small explanation to create your own testing data.
> 
> It is necessary that your Source and Target meshes have the same number of vertices and same vertex topology! For example, a vertex on the mouth corner of the Source mesh corresponds to the same vertex on the same mouth corner on the Target mesh.
> 
> * Place your source_neutral.obj and all of the source blendshapes (source_blendshape_1.obj ... source_blendshape_n.obj) in meshes/
> * Place the target_neutral.obj in target_meshes/
> * To create data for the symmetries/ folder, please open either your source_neutral.obj or target_neutral.obj in Maya. Use the paint select tool to select the top area of the left eye. Export these vertex numbers to a .txt file. Clear selection. Select the bottom area of the left eye. Export. Clear.
>   
>   * Repeat this for each of the following areas: Eye Left Top, Eye Left Bottom, Eye Right Top, Eye Right Bottom, Mouth Top, Mouth Bottom, Face Left, Face Right.
>   * To select Face Left and Face Right, if your mesh is symmetric around the vertical axis (as most face meshes are!), I suggest using Maya's symmetry select.
>   * Save these .txt files as character_sym0.txt, character_sym1.txt ... character_sym7.txt in symmetries/
> 
> I hope this helps! :D

Hi!

Thanks for your reply!! I will do some experiment according to your suggestion!!

**Comment by wuyunnben** [comment]
I run the program with your pipeline, however, it need a file called symmetric_vertex_pairs.txt. Can your help me, thanks.
